name=signalk-mini
version=0.1.0
author=Bareboat Necessities
maintainer=Bareboat Necessities
sentence=Lightweight Signal K mini server for Arduino and Linux.
paragraph=Signal K mini server using a strongly typed data model, async event loop, NMEA connectors, and ArduinoJson.
category=Communication
url=https://github.com/bareboat-necessities/signalk-mini
architectures=esp32
depends=M5Unified,ArduinoJson
includes=signalk_mini.hpp
