#pragma once

#include <stddef.h>

namespace ship_data_model {

enum class FieldId {
    unknown,
    compat_value,
    server_version,
    server_uptime_s,
    status_last_error,
    ap_enabled,
    ap_mode,
    ap_pilot,
    ap_heading_deg,
    ap_tack_progress_0_1,
    wind_source,
    wind_filtered_direction_deg,
    servo_current_a,
    servo_telemetry_current_a,
    servo_flags,
    servo_telemetry_state,
    rudder_calibration_state,
    imu_calibration_heading_offset_deg,
    pilot_basic_P,
    pilot_basic_Pgain
};

enum class FieldType {
    number,
    integer,
    boolean,
    string_value,
    json_value,
    mode_enum,
    pilot_enum,
    source_enum,
    rudder_calibration_enum,
    servo_state_enum,
    tack_state_enum,
    tack_direction_enum,
    vector3_value,
    quaternion_value,
    unknown_value
};

struct FieldMeta {
    FieldId id;
    const char* pypilot_name;
    const char* unit;
    FieldType type;
    bool writable;
    bool persistent;
    bool pilot_specific;
};

// Field metadata mirrors pypilot runtime Value registrations.
// Names with dedicated DataModel storage use a concrete FieldId.
// Other known pypilot runtime names use compat_value but still keep their
// own type, unit, writable, persistent, and pilot-specific metadata.
static constexpr FieldMeta field_definitions[] = {
    {FieldId::compat_value, "compat.value", "", FieldType::unknown_value, false, false, false},
    {FieldId::server_version, "server.version", "", FieldType::string_value, false, false, false},
    {FieldId::server_uptime_s, "server.uptime", "s", FieldType::number, false, false, false},
    {FieldId::status_last_error, "status.last_error", "", FieldType::string_value, false, false, false},
    {FieldId::ap_tack_progress_0_1, "ap.tack.progress", "", FieldType::number, false, false, false},
    {FieldId::servo_telemetry_current_a, "servo.telemetry.current", "A", FieldType::number, false, false, false},
    {FieldId::server_version, "ap.version", "", FieldType::string_value, false, false, false},
    {FieldId::compat_value, "ap.preferred_mode", "", FieldType::mode_enum, false, false, false},
    {FieldId::ap_mode, "ap.mode", "", FieldType::mode_enum, true, true, false},
    {FieldId::compat_value, "ap.modes", "", FieldType::json_value, false, false, false},
    {FieldId::compat_value, "ap.gps_and_nav_modes", "", FieldType::boolean, true, true, false},
    {FieldId::compat_value, "ap.heading_command", "deg", FieldType::number, true, false, false},
    {FieldId::ap_enabled, "ap.enabled", "", FieldType::boolean, true, false, false},
    {FieldId::ap_heading_deg, "ap.heading", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "ap.heading_error", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "ap.heading_error_int", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "ap.heading_command_rate", "deg/s", FieldType::number, false, false, false},
    {FieldId::ap_pilot, "ap.pilot", "", FieldType::pilot_enum, true, true, false},
    {FieldId::compat_value, "ap.gps_compass_offset", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "ap.wind_compass_offset", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "ap.true_wind_compass_offset", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "ap.wind_offset_filter", "", FieldType::number, true, true, false},
    {FieldId::compat_value, "ap.runtime", "s", FieldType::number, false, false, false},
    {FieldId::compat_value, "ap.timings", "", FieldType::json_value, false, false, false},
    {FieldId::compat_value, "imu.rate", "Hz", FieldType::integer, true, true, false},
    {FieldId::compat_value, "imu.frequency", "Hz", FieldType::number, false, false, false},
    {FieldId::compat_value, "imu.alignmentQ", "", FieldType::quaternion_value, true, true, false},
    {FieldId::imu_calibration_heading_offset_deg, "imu.heading_offset", "deg", FieldType::number, true, true, false},
    {FieldId::compat_value, "imu.alignmentCounter", "", FieldType::integer, true, false, false},
    {FieldId::compat_value, "imu.uptime", "s", FieldType::number, false, false, false},
    {FieldId::compat_value, "imu.warning", "", FieldType::string_value, false, false, false},
    {FieldId::compat_value, "imu.heading_lowpass_constant", "", FieldType::number, true, false, false},
    {FieldId::compat_value, "imu.headingrate_lowpass_constant", "", FieldType::number, true, false, false},
    {FieldId::compat_value, "imu.headingraterate_lowpass_constant", "", FieldType::number, true, false, false},
    {FieldId::compat_value, "imu.accel", "", FieldType::vector3_value, false, false, false},
    {FieldId::compat_value, "imu.gyro", "", FieldType::vector3_value, false, false, false},
    {FieldId::compat_value, "imu.compass", "", FieldType::vector3_value, false, false, false},
    {FieldId::compat_value, "imu.accel.residuals", "", FieldType::vector3_value, false, false, false},
    {FieldId::compat_value, "imu.pitch", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "imu.roll", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "imu.fusionQPose", "", FieldType::quaternion_value, false, false, false},
    {FieldId::compat_value, "imu.heading", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "imu.heading_lowpass", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "imu.headingrate", "deg/s", FieldType::number, false, false, false},
    {FieldId::compat_value, "imu.headingrate_lowpass", "deg/s", FieldType::number, false, false, false},
    {FieldId::compat_value, "imu.headingraterate", "deg/s", FieldType::number, false, false, false},
    {FieldId::compat_value, "imu.headingraterate_lowpass", "deg/s", FieldType::number, false, false, false},
    {FieldId::compat_value, "imu.pitchrate", "deg/s", FieldType::number, false, false, false},
    {FieldId::compat_value, "imu.rollrate", "deg/s", FieldType::number, false, false, false},
    {FieldId::compat_value, "imu.gyrobias", "", FieldType::vector3_value, false, true, false},
    {FieldId::compat_value, "gps.source", "", FieldType::source_enum, false, false, false},
    {FieldId::compat_value, "gps.rate", "Hz", FieldType::number, true, true, false},
    {FieldId::compat_value, "gps.track", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "gps.speed", "kn", FieldType::number, false, false, false},
    {FieldId::compat_value, "gps.fix", "", FieldType::json_value, false, false, false},
    {FieldId::compat_value, "gps.leeway_ground", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "gps.compass_error", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "gps.declination", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "gps.alignmentCounter", "", FieldType::integer, true, false, false},
    {FieldId::wind_source, "wind.source", "", FieldType::source_enum, false, false, false},
    {FieldId::compat_value, "wind.rate", "Hz", FieldType::number, true, true, false},
    {FieldId::compat_value, "wind.direction", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "wind.speed", "kn", FieldType::number, false, false, false},
    {FieldId::compat_value, "wind.offset", "deg", FieldType::number, true, true, false},
    {FieldId::compat_value, "wind.sensors_height", "m", FieldType::number, true, true, false},
    {FieldId::compat_value, "wind.filtered_speed", "kn", FieldType::number, false, false, false},
    {FieldId::wind_filtered_direction_deg, "wind.filtered_direction", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "wind.filter_constant", "", FieldType::number, true, true, false},
    {FieldId::compat_value, "wind.filter_factor", "", FieldType::number, false, false, false},
    {FieldId::compat_value, "truewind.source", "", FieldType::source_enum, false, false, false},
    {FieldId::compat_value, "truewind.rate", "Hz", FieldType::number, true, true, false},
    {FieldId::compat_value, "truewind.direction", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "truewind.speed", "kn", FieldType::number, false, false, false},
    {FieldId::compat_value, "truewind.offset", "deg", FieldType::number, true, true, false},
    {FieldId::compat_value, "truewind.sensors_height", "m", FieldType::number, true, true, false},
    {FieldId::compat_value, "truewind.filtered_speed", "kn", FieldType::number, false, false, false},
    {FieldId::compat_value, "truewind.filtered_direction", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "truewind.filter_constant", "", FieldType::number, true, true, false},
    {FieldId::compat_value, "truewind.filter_factor", "", FieldType::number, false, false, false},
    {FieldId::compat_value, "apb.source", "", FieldType::source_enum, false, false, false},
    {FieldId::compat_value, "apb.track", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "apb.xte", "nmi", FieldType::number, false, false, false},
    {FieldId::compat_value, "apb.xte.gain", "deg/nmi", FieldType::number, true, true, false},
    {FieldId::compat_value, "water.source", "", FieldType::source_enum, false, false, false},
    {FieldId::compat_value, "water.rate", "Hz", FieldType::number, true, true, false},
    {FieldId::compat_value, "water.speed", "kn", FieldType::number, false, false, false},
    {FieldId::compat_value, "water.leeway", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "water.leeway.source", "", FieldType::source_enum, false, false, false},
    {FieldId::compat_value, "water.current.speed", "kn", FieldType::number, false, false, false},
    {FieldId::compat_value, "water.current.direction", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "water.wind.speed", "kn", FieldType::number, false, false, false},
    {FieldId::compat_value, "water.wind.direction", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "rudder.source", "", FieldType::source_enum, false, false, false},
    {FieldId::compat_value, "rudder.rate", "Hz", FieldType::number, true, false, false},
    {FieldId::compat_value, "rudder.angle", "deg", FieldType::number, false, false, false},
    {FieldId::compat_value, "rudder.speed", "deg/s", FieldType::number, false, false, false},
    {FieldId::compat_value, "rudder.offset", "deg", FieldType::number, false, true, false},
    {FieldId::compat_value, "rudder.scale", "", FieldType::number, false, true, false},
    {FieldId::compat_value, "rudder.nonlinearity", "", FieldType::number, false, true, false},
    {FieldId::rudder_calibration_state, "rudder.calibration_state", "", FieldType::rudder_calibration_enum, true, false, false},
    {FieldId::compat_value, "rudder.range", "deg", FieldType::number, true, true, false},
    {FieldId::compat_value, "servo.calibration", "", FieldType::json_value, false, false, false},
    {FieldId::compat_value, "servo.position_command", "", FieldType::number, true, false, false},
    {FieldId::compat_value, "servo.command", "", FieldType::number, true, false, false},
    {FieldId::compat_value, "servo.speed_gain", "", FieldType::number, true, false, false},
    {FieldId::compat_value, "servo.duty", "", FieldType::number, false, false, false},
    {FieldId::compat_value, "servo.faults", "", FieldType::integer, true, true, false},
    {FieldId::compat_value, "servo.voltage", "V", FieldType::number, false, false, false},
    {FieldId::servo_current_a, "servo.current", "A", FieldType::number, false, false, false},
    {FieldId::compat_value, "servo.current.noise", "A", FieldType::number, false, false, false},
    {FieldId::compat_value, "servo.controller_temp", "C", FieldType::number, false, false, false},
    {FieldId::compat_value, "servo.motor_temp", "C", FieldType::number, false, false, false},
    {FieldId::compat_value, "servo.engaged", "", FieldType::boolean, false, false, false},
    {FieldId::compat_value, "servo.max_current", "A", FieldType::number, true, true, false},
    {FieldId::compat_value, "servo.current.factor", "", FieldType::number, true, true, false},
    {FieldId::compat_value, "servo.current.offset", "A", FieldType::number, true, true, false},
    {FieldId::compat_value, "servo.voltage.factor", "", FieldType::number, true, true, false},
    {FieldId::compat_value, "servo.voltage.offset", "V", FieldType::number, true, true, false},
    {FieldId::compat_value, "servo.max_controller_temp", "C", FieldType::number, true, true, false},
    {FieldId::compat_value, "servo.max_motor_temp", "C", FieldType::number, true, true, false},
    {FieldId::compat_value, "servo.max_slew_speed", "%", FieldType::number, true, true, false},
    {FieldId::compat_value, "servo.max_slew_slow", "%", FieldType::number, true, true, false},
    {FieldId::compat_value, "servo.gain", "", FieldType::number, true, true, false},
    {FieldId::compat_value, "servo.clutch_pwm", "%", FieldType::number, true, true, false},
    {FieldId::compat_value, "servo.use_brake", "", FieldType::boolean, true, true, false},
    {FieldId::compat_value, "servo.period", "s", FieldType::number, true, true, false},
    {FieldId::compat_value, "servo.compensate_current", "", FieldType::boolean, true, true, false},
    {FieldId::compat_value, "servo.compensate_voltage", "", FieldType::boolean, true, true, false},
    {FieldId::compat_value, "servo.amp_hours", "Ah", FieldType::number, true, true, false},
    {FieldId::compat_value, "servo.watts", "W", FieldType::number, false, false, false},
    {FieldId::compat_value, "servo.speed", "", FieldType::number, false, false, false},
    {FieldId::compat_value, "servo.speed.min", "%", FieldType::number, true, true, false},
    {FieldId::compat_value, "servo.speed.max", "%", FieldType::number, true, true, false},
    {FieldId::compat_value, "servo.position", "", FieldType::number, false, false, false},
    {FieldId::compat_value, "servo.position.p", "", FieldType::number, true, true, false},
    {FieldId::compat_value, "servo.position.i", "", FieldType::number, true, true, false},
    {FieldId::compat_value, "servo.position.d", "", FieldType::number, true, true, false},
    {FieldId::compat_value, "servo.raw_command", "", FieldType::number, false, false, false},
    {FieldId::compat_value, "servo.use_eeprom", "", FieldType::boolean, false, true, false},
    {FieldId::servo_telemetry_state, "servo.state", "", FieldType::string_value, false, false, false},
    {FieldId::compat_value, "servo.controller", "", FieldType::string_value, false, false, false},
    {FieldId::servo_flags, "servo.flags", "", FieldType::integer, false, false, false},
    {FieldId::compat_value, "ap.tack.state", "", FieldType::tack_state_enum, true, false, false},
    {FieldId::compat_value, "ap.tack.timeout", "s", FieldType::number, false, false, false},
    {FieldId::compat_value, "ap.tack.delay", "s", FieldType::number, true, true, false},
    {FieldId::compat_value, "ap.tack.angle", "deg", FieldType::number, true, true, false},
    {FieldId::compat_value, "ap.tack.rate", "deg/s", FieldType::number, true, true, false},
    {FieldId::compat_value, "ap.tack.threshold", "%", FieldType::number, true, true, false},
    {FieldId::compat_value, "ap.tack.count", "", FieldType::integer, true, true, false},
    {FieldId::compat_value, "ap.tack.direction", "", FieldType::tack_direction_enum, true, false, false},
    {FieldId::compat_value, "ap.tack.use_heel", "", FieldType::boolean, true, true, false},
    {FieldId::compat_value, "ap.tack.use_wind_direction", "", FieldType::boolean, true, true, false},
    {FieldId::pilot_basic_P, "ap.pilot.basic.P", "", FieldType::number, true, true, true},
    {FieldId::pilot_basic_Pgain, "ap.pilot.basic.Pgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.basic.D", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.basic.Dgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.basic.DD", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.basic.DDgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.basic.PR", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.basic.PRgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.basic.FF", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.basic.FFgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.wind.gps_wind_offset", "deg", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.wind.P", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.wind.Pgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.wind.D", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.wind.Dgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.wind.DD", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.wind.DDgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.wind.WG", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.wind.WGgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.absolute.P", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.absolute.Pgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.absolute.I", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.absolute.Igain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.absolute.D", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.absolute.Dgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.absolute.FF", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.absolute.FFgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.rate.D", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.rate.Dgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.rate.DD", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.rate.DDgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.rate.FF", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.rate.FFgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.rate.maxturnrate", "deg/s", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.rate.turnraterate", "deg/s", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.simple.P", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.simple.Pgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.simple.I", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.simple.Igain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.simple.D", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.simple.Dgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.vmg.P", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.vmg.Pgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.vmg.D", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.vmg.Dgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.vmg.DD", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.vmg.DDgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.deadzone.deadzone", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.fuzzy.learningP", "", FieldType::number, true, false, true},
    {FieldId::compat_value, "ap.pilot.fuzzy.learningD", "", FieldType::number, true, false, true},
    {FieldId::compat_value, "ap.pilot.fuzzy.seastate", "", FieldType::number, false, false, true},
    {FieldId::pilot_basic_P, "ap.pilot.learning.P", "", FieldType::number, true, true, true},
    {FieldId::pilot_basic_Pgain, "ap.pilot.learning.Pgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.learning.D", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.learning.Dgain", "", FieldType::number, false, false, true},
    {FieldId::compat_value, "ap.pilot.learning.W", "", FieldType::number, true, true, true},
    {FieldId::compat_value, "ap.pilot.learning.Wgain", "", FieldType::number, false, false, true},
};

static constexpr size_t field_definition_count = sizeof(field_definitions) / sizeof(field_definitions[0]);

} // namespace ship_data_model
