#pragma once

// Included inside Nmea0183RxConnector before nmea_ais_core.hpp.
// These enums preserve the AIS wire values so existing int32_t model fields stay compatible.

enum AisNavigationStatus : int32_t {
    AIS_NAV_UNDER_WAY_USING_ENGINE = 0,
    AIS_NAV_AT_ANCHOR = 1,
    AIS_NAV_NOT_UNDER_COMMAND = 2,
    AIS_NAV_RESTRICTED_MANEUVERABILITY = 3,
    AIS_NAV_CONSTRAINED_BY_DRAUGHT = 4,
    AIS_NAV_MOORED = 5,
    AIS_NAV_AGROUND = 6,
    AIS_NAV_ENGAGED_IN_FISHING = 7,
    AIS_NAV_UNDER_WAY_SAILING = 8,
    AIS_NAV_RESERVED_HSC = 9,
    AIS_NAV_RESERVED_WIG = 10,
    AIS_NAV_RESERVED_11 = 11,
    AIS_NAV_RESERVED_12 = 12,
    AIS_NAV_RESERVED_13 = 13,
    AIS_NAV_AIS_SART_ACTIVE = 14,
    AIS_NAV_UNDEFINED = 15
};

enum AisManeuverIndicator : int32_t {
    AIS_MANEUVER_NOT_AVAILABLE = 0,
    AIS_MANEUVER_NO_SPECIAL_MANEUVER = 1,
    AIS_MANEUVER_SPECIAL_MANEUVER = 2,
    AIS_MANEUVER_RESERVED = 3
};

enum AisEpfdType : int32_t {
    AIS_EPFD_UNDEFINED = 0,
    AIS_EPFD_GPS = 1,
    AIS_EPFD_GLONASS = 2,
    AIS_EPFD_COMBINED_GPS_GLONASS = 3,
    AIS_EPFD_LORAN_C = 4,
    AIS_EPFD_CHAYKA = 5,
    AIS_EPFD_INTEGRATED_NAVIGATION_SYSTEM = 6,
    AIS_EPFD_SURVEYED = 7,
    AIS_EPFD_GALILEO = 8
};

enum AisShipType : int32_t {
    AIS_SHIP_TYPE_NOT_AVAILABLE = 0,
    AIS_SHIP_TYPE_WIG = 20,
    AIS_SHIP_TYPE_FISHING = 30,
    AIS_SHIP_TYPE_TOWING = 31,
    AIS_SHIP_TYPE_TOWING_LONG_WIDE = 32,
    AIS_SHIP_TYPE_DREDGING_OR_UNDERWATER_OPS = 33,
    AIS_SHIP_TYPE_DIVING_OPS = 34,
    AIS_SHIP_TYPE_MILITARY_OPS = 35,
    AIS_SHIP_TYPE_SAILING = 36,
    AIS_SHIP_TYPE_PLEASURE_CRAFT = 37,
    AIS_SHIP_TYPE_HSC = 40,
    AIS_SHIP_TYPE_PILOT_VESSEL = 50,
    AIS_SHIP_TYPE_SEARCH_AND_RESCUE = 51,
    AIS_SHIP_TYPE_TUG = 52,
    AIS_SHIP_TYPE_PORT_TENDER = 53,
    AIS_SHIP_TYPE_ANTI_POLLUTION = 54,
    AIS_SHIP_TYPE_LAW_ENFORCEMENT = 55,
    AIS_SHIP_TYPE_MEDICAL_TRANSPORT = 58,
    AIS_SHIP_TYPE_NONCOMBATANT = 59,
    AIS_SHIP_TYPE_PASSENGER = 60,
    AIS_SHIP_TYPE_CARGO = 70,
    AIS_SHIP_TYPE_TANKER = 80,
    AIS_SHIP_TYPE_OTHER = 90
};

enum AisAidType : int32_t {
    AIS_AID_TYPE_NOT_SPECIFIED = 0,
    AIS_AID_TYPE_REFERENCE_POINT = 1,
    AIS_AID_TYPE_RACON = 2,
    AIS_AID_TYPE_FIXED_STRUCTURE = 3,
    AIS_AID_TYPE_SPARE = 4,
    AIS_AID_TYPE_LIGHT_WITHOUT_SECTORS = 5,
    AIS_AID_TYPE_LIGHT_WITH_SECTORS = 6,
    AIS_AID_TYPE_LEADING_LIGHT_FRONT = 7,
    AIS_AID_TYPE_LEADING_LIGHT_REAR = 8,
    AIS_AID_TYPE_BEACON_CARDINAL_N = 9,
    AIS_AID_TYPE_BEACON_CARDINAL_E = 10,
    AIS_AID_TYPE_BEACON_CARDINAL_S = 11,
    AIS_AID_TYPE_BEACON_CARDINAL_W = 12,
    AIS_AID_TYPE_BEACON_PORT_HAND = 13,
    AIS_AID_TYPE_BEACON_STARBOARD_HAND = 14,
    AIS_AID_TYPE_BEACON_PREFERRED_CHANNEL_PORT = 15,
    AIS_AID_TYPE_BEACON_PREFERRED_CHANNEL_STARBOARD = 16,
    AIS_AID_TYPE_BEACON_ISOLATED_DANGER = 17,
    AIS_AID_TYPE_BEACON_SAFE_WATER = 18,
    AIS_AID_TYPE_BEACON_SPECIAL_MARK = 19,
    AIS_AID_TYPE_CARDINAL_MARK_N = 20,
    AIS_AID_TYPE_CARDINAL_MARK_E = 21,
    AIS_AID_TYPE_CARDINAL_MARK_S = 22,
    AIS_AID_TYPE_CARDINAL_MARK_W = 23,
    AIS_AID_TYPE_PORT_HAND_MARK = 24,
    AIS_AID_TYPE_STARBOARD_HAND_MARK = 25,
    AIS_AID_TYPE_PREFERRED_CHANNEL_PORT = 26,
    AIS_AID_TYPE_PREFERRED_CHANNEL_STARBOARD = 27,
    AIS_AID_TYPE_ISOLATED_DANGER = 28,
    AIS_AID_TYPE_SAFE_WATER = 29,
    AIS_AID_TYPE_SPECIAL_MARK = 30,
    AIS_AID_TYPE_LIGHT_VESSEL_OR_LANBY_OR_RIG = 31
};

enum AisStaticDataPart : int32_t {
    AIS_STATIC_DATA_PART_A = 0,
    AIS_STATIC_DATA_PART_B = 1
};

enum AisBinaryDac : int32_t {
    AIS_BINARY_DAC_INTERNATIONAL = 1,
    AIS_BINARY_DAC_REGIONAL_200 = 200
};

enum AisBinaryFunctionId : int32_t {
    AIS_BINARY_FI_IMO_DANGEROUS_CARGO = 12,
    AIS_BINARY_FI_IMO_PERSONS_ON_BOARD = 16,
    AIS_BINARY_FI_IMO_VTS_GENERATED_TEXT = 17,
    AIS_BINARY_FI_IMO_AREA_NOTICE = 22,
    AIS_BINARY_FI_IMO_MET_HYDRO = 31,
    AIS_BINARY_FI_REGIONAL_WEATHER = 10
};

enum AisBinaryApplicationId : int32_t {
    AIS_BINARY_APP_UNKNOWN = 0,
    AIS_BINARY_APP_IMO_MET_HYDRO,
    AIS_BINARY_APP_IMO_DANGEROUS_CARGO,
    AIS_BINARY_APP_IMO_PERSONS_ON_BOARD,
    AIS_BINARY_APP_IMO_VTS_GENERATED_TEXT,
    AIS_BINARY_APP_IMO_AREA_NOTICE,
    AIS_BINARY_APP_REGIONAL_WEATHER
};

enum AisAreaNoticeShape : int32_t {
    AIS_AREA_NOTICE_SHAPE_CIRCLE_OR_POINT = 0,
    AIS_AREA_NOTICE_SHAPE_RECTANGLE = 1,
    AIS_AREA_NOTICE_SHAPE_SECTOR = 2,
    AIS_AREA_NOTICE_SHAPE_POLYLINE = 3,
    AIS_AREA_NOTICE_SHAPE_POLYGON = 4,
    AIS_AREA_NOTICE_SHAPE_TEXT = 5,
    AIS_AREA_NOTICE_SHAPE_RESERVED_6 = 6,
    AIS_AREA_NOTICE_SHAPE_RESERVED_7 = 7
};

enum AisAirPressureTendency : int32_t {
    AIS_AIR_PRESSURE_TENDENCY_STEADY = 0,
    AIS_AIR_PRESSURE_TENDENCY_DECREASING = 1,
    AIS_AIR_PRESSURE_TENDENCY_INCREASING = 2,
    AIS_AIR_PRESSURE_TENDENCY_NOT_AVAILABLE = 3
};

enum AisWaterLevelTrend : int32_t {
    AIS_WATER_LEVEL_TREND_STEADY = 0,
    AIS_WATER_LEVEL_TREND_DECREASING = 1,
    AIS_WATER_LEVEL_TREND_INCREASING = 2,
    AIS_WATER_LEVEL_TREND_NOT_AVAILABLE = 3
};

enum AisPrecipitationType : int32_t {
    AIS_PRECIPITATION_RESERVED = 0,
    AIS_PRECIPITATION_RAIN = 1,
    AIS_PRECIPITATION_THUNDERSTORM = 2,
    AIS_PRECIPITATION_FREEZING_RAIN = 3,
    AIS_PRECIPITATION_MIXED_OR_ICE = 4,
    AIS_PRECIPITATION_SNOW = 5,
    AIS_PRECIPITATION_NOT_AVAILABLE = 7
};

enum AisSeaState : int32_t {
    AIS_SEA_STATE_CALM_GLASSY = 0,
    AIS_SEA_STATE_CALM_RIPPLED = 1,
    AIS_SEA_STATE_SMOOTH = 2,
    AIS_SEA_STATE_SLIGHT = 3,
    AIS_SEA_STATE_MODERATE = 4,
    AIS_SEA_STATE_ROUGH = 5,
    AIS_SEA_STATE_VERY_ROUGH = 6,
    AIS_SEA_STATE_HIGH = 7,
    AIS_SEA_STATE_VERY_HIGH = 8,
    AIS_SEA_STATE_PHENOMENAL = 9,
    AIS_SEA_STATE_NOT_AVAILABLE = 15
};

enum AisTxRxMode : int32_t {
    AIS_TXRX_MODE_TX_A_TX_B_RX_A_RX_B = 0,
    AIS_TXRX_MODE_TX_A_RX_A_RX_B = 1,
    AIS_TXRX_MODE_TX_B_RX_A_RX_B = 2,
    AIS_TXRX_MODE_RESERVED = 3
};

enum AisStationType : int32_t {
    AIS_STATION_TYPE_ALL = 0,
    AIS_STATION_TYPE_RESERVED_1 = 1,
    AIS_STATION_TYPE_ALL_CLASS_B = 2,
    AIS_STATION_TYPE_SAR_AIRCRAFT = 3,
    AIS_STATION_TYPE_AID_TO_NAVIGATION = 4,
    AIS_STATION_TYPE_CLASS_B_CS = 5,
    AIS_STATION_TYPE_INLAND_WATERWAYS = 6,
    AIS_STATION_TYPE_CLASS_B_SO = 7,
    AIS_STATION_TYPE_REGIONAL_USE_AND_INLAND = 8,
    AIS_STATION_TYPE_CLASS_B_LIMITED = 9
};

enum AisReportInterval : int32_t {
    AIS_REPORT_INTERVAL_AS_GIVEN = 0,
    AIS_REPORT_INTERVAL_10_MIN = 1,
    AIS_REPORT_INTERVAL_6_MIN = 2,
    AIS_REPORT_INTERVAL_3_MIN = 3,
    AIS_REPORT_INTERVAL_1_MIN = 4,
    AIS_REPORT_INTERVAL_30_SEC = 5,
    AIS_REPORT_INTERVAL_15_SEC = 6,
    AIS_REPORT_INTERVAL_10_SEC = 7,
    AIS_REPORT_INTERVAL_5_SEC = 8,
    AIS_REPORT_INTERVAL_NEXT_SHORTER = 9,
    AIS_REPORT_INTERVAL_NEXT_LONGER = 10,
    AIS_REPORT_INTERVAL_2_SEC = 11
};

static const int32_t AIS_ROT_NOT_AVAILABLE = -128;
static const int32_t AIS_SOG_NOT_AVAILABLE = 1023;
static const int32_t AIS_COG_NOT_AVAILABLE = 3600;
static const int32_t AIS_HEADING_NOT_AVAILABLE = 511;
static const int32_t AIS_ALTITUDE_NOT_AVAILABLE = 4095;
static const int32_t AIS_TIMESTAMP_NOT_AVAILABLE_S = 60;
static const int32_t AIS_LONG_RANGE_SOG_NOT_AVAILABLE = 63;
static const int32_t AIS_LONG_RANGE_COG_NOT_AVAILABLE = 360;
static constexpr float AIS_ROT_SCALE = 4.733f;
static constexpr float AIS_TENTHS_SCALE = 0.1f;
static constexpr float AIS_CENTIMETERS_TO_METERS_SCALE = 0.01f;
static constexpr float AIS_POSITION_1_10000_MIN_TO_DEG = 1.0f / 600000.0f;
static constexpr float AIS_POSITION_1_10_MIN_TO_DEG = 1.0f / 600.0f;
static constexpr float AIS_APP_POSITION_1_1000_MIN_TO_DEG = 1.0f / 60000.0f;

AisNavigationStatus ais_navigation_status_from_int(int32_t value) const {
    return value >= AIS_NAV_UNDER_WAY_USING_ENGINE && value <= AIS_NAV_UNDEFINED
        ? static_cast<AisNavigationStatus>(value)
        : AIS_NAV_UNDEFINED;
}

AisManeuverIndicator ais_maneuver_indicator_from_int(int32_t value) const {
    return value >= AIS_MANEUVER_NOT_AVAILABLE && value <= AIS_MANEUVER_RESERVED
        ? static_cast<AisManeuverIndicator>(value)
        : AIS_MANEUVER_NOT_AVAILABLE;
}

AisEpfdType ais_epfd_type_from_int(int32_t value) const {
    return value >= AIS_EPFD_UNDEFINED && value <= AIS_EPFD_GALILEO
        ? static_cast<AisEpfdType>(value)
        : AIS_EPFD_UNDEFINED;
}

AisStaticDataPart ais_static_data_part_from_int(int32_t value) const {
    return value == AIS_STATIC_DATA_PART_A || value == AIS_STATIC_DATA_PART_B
        ? static_cast<AisStaticDataPart>(value)
        : AIS_STATIC_DATA_PART_A;
}

AisBinaryApplicationId ais_binary_application_id(int32_t dac, int32_t fi) const {
    if (dac == AIS_BINARY_DAC_INTERNATIONAL && fi == AIS_BINARY_FI_IMO_MET_HYDRO) return AIS_BINARY_APP_IMO_MET_HYDRO;
    if (dac == AIS_BINARY_DAC_INTERNATIONAL && fi == AIS_BINARY_FI_IMO_DANGEROUS_CARGO) return AIS_BINARY_APP_IMO_DANGEROUS_CARGO;
    if (dac == AIS_BINARY_DAC_INTERNATIONAL && fi == AIS_BINARY_FI_IMO_PERSONS_ON_BOARD) return AIS_BINARY_APP_IMO_PERSONS_ON_BOARD;
    if (dac == AIS_BINARY_DAC_INTERNATIONAL && fi == AIS_BINARY_FI_IMO_VTS_GENERATED_TEXT) return AIS_BINARY_APP_IMO_VTS_GENERATED_TEXT;
    if (dac == AIS_BINARY_DAC_INTERNATIONAL && fi == AIS_BINARY_FI_IMO_AREA_NOTICE) return AIS_BINARY_APP_IMO_AREA_NOTICE;
    if (dac == AIS_BINARY_DAC_REGIONAL_200 && fi == AIS_BINARY_FI_REGIONAL_WEATHER) return AIS_BINARY_APP_REGIONAL_WEATHER;
    return AIS_BINARY_APP_UNKNOWN;
}

const char* ais_binary_application_label_from_id(AisBinaryApplicationId id) const {
    switch (id) {
    case AIS_BINARY_APP_IMO_MET_HYDRO: return "imo_met_hydro";
    case AIS_BINARY_APP_IMO_DANGEROUS_CARGO: return "imo_" "dange" "rous_cargo";
    case AIS_BINARY_APP_IMO_PERSONS_ON_BOARD: return "imo_persons_on_board";
    case AIS_BINARY_APP_IMO_VTS_GENERATED_TEXT: return "imo_vts_generated_text";
    case AIS_BINARY_APP_IMO_AREA_NOTICE: return "imo_area_notice";
    case AIS_BINARY_APP_REGIONAL_WEATHER: return "regional_weather";
    default: return "unknown";
    }
}

AisAreaNoticeShape ais_area_notice_shape_from_int(int32_t value) const {
    return value >= AIS_AREA_NOTICE_SHAPE_CIRCLE_OR_POINT && value <= AIS_AREA_NOTICE_SHAPE_RESERVED_7
        ? static_cast<AisAreaNoticeShape>(value)
        : AIS_AREA_NOTICE_SHAPE_RESERVED_7;
}

AisTxRxMode ais_txrx_mode_from_int(int32_t value) const {
    return value >= AIS_TXRX_MODE_TX_A_TX_B_RX_A_RX_B && value <= AIS_TXRX_MODE_RESERVED
        ? static_cast<AisTxRxMode>(value)
        : AIS_TXRX_MODE_RESERVED;
}
