#pragma once

#include <stdint.h>

namespace signalk_mini {

using SourceId = uint16_t;

enum class ModelField : uint16_t {
    None = 0,
    GnssFixLatDeg,
    GnssFixLonDeg,
    GnssSpeedKn,
    GnssTrackDeg,
    GnssTimestampS,
    GnssDateDay,
    GnssDateMonth,
    GnssDateYear,
    GnssFixQuality,
    GnssSatellitesUsed,
    GnssHdop,
    GnssDgpsStationId,
    GnssDeclinationDeg,
    GnssFixAltitudeM,
    GnssGeoidalSeparationM,
    GnssDgpsAgeS,
    GnssFixAccuracyHorizontalM,
    GnssFixAccuracyVerticalM,
    GnssFixAccuracyPdop,
    GnssFixAccuracyVdop,
    GnssDopActiveFixMode,
    GnssDopActivePdop,
    GnssDopActiveVdop,
    GnssSatellitesInView,
    GnssSatellitePrn0,
    GnssSatelliteElevationDeg0,
    GnssSatelliteAzimuthDeg0,
    GnssSatelliteSnrDb0,

    ImuHeadingDeg,
    ImuHeadingTrueDeg,
    ImuHeadingMagneticDeg,
    ImuMagneticVariationDeg,
    ImuMagneticDeviationDeg,
    ImuPitchDeg,
    ImuRollDeg,

    WindApparentDirectionDeg,
    WindApparentSpeedKn,
    WindTrueDirectionDeg,
    WindTrueDirectionMagneticDeg,
    WindTrueSpeedKn,
    WindTrueSpeedMs,
    WindSurfaceDirectionDeg,
    WindSurfaceDirectionMagneticDeg,
    WindSurfaceSpeedKn,
    WindSurfaceSpeedMs,

    EnvBarometricPressureBar,
    EnvBarometricPressureInHg,
    EnvAirTemperatureC,
    EnvRelativeHumidityPercent,
    EnvAbsoluteHumidityPercent,
    EnvDewPointC,

    SeaSpeedKn,
    SeaLongitudinalWaterSpeedKn,
    SeaTransverseWaterSpeedKn,
    SeaLongitudinalGroundSpeedKn,
    SeaTransverseGroundSpeedKn,
    SeaSpeedParallelToWindKn,
    SeaSpeedParallelToWindMs,
    SeaLeewayDeg,
    SeaCurrentSpeedKn,
    SeaCurrentDirectionDeg,
    SeaCurrentDirectionMagneticDeg,
    SeaTemperatureC,
    SeaDepthM,
    SeaDepthBelowKeelM,
    SeaDepthBelowSurfaceM,
    SeaDepthOffsetM,

    SteeringRudderAngleDeg,

    PropulsionRevolutionsNumber,
    PropulsionRevolutionsSpeedRpm,
    PropulsionRevolutionsPitchPercent,

    AutopilotMode,
    AutopilotEnabled,
    AutopilotHeadingDeg,
    AutopilotHeadingCommandDeg,
    AutopilotWarnings,

    RouteActiveWaypointCount,
    RouteLogTotalDistanceNmi,
    RouteLogTripDistanceNmi,
    RouteHeadingSteeringCommandTrueDeg,
    RouteHeadingSteeringCommandMagneticDeg,
    RouteApbXteNmi,
    RouteApbOriginToDestinationBearingDeg,
    RouteApbPresentToDestinationBearingDeg,
    RouteApbHeadingToSteerDeg,
    RouteApbArrivalCircleEntered,
    RouteApbPerpendicularPassed,
    RouteApbDestinationId,
    RouteRmbXteNmi,
    RouteRmbDestinationLatDeg,
    RouteRmbDestinationLonDeg,
    RouteRmbRangeNmi,
    RouteRmbBearingDeg,
    RouteRmbClosingVelocityKn,
    RouteRmbArrived,
    RouteRmbDestinationId,
    RouteWaypointUtcTimeS,
    RouteWaypointOriginUtcTimeS,
    RouteWaypointOriginElapsedTimeS,
    RouteWaypointDestinationUtcTimeS,
    RouteWaypointDestinationTimeRemainingS,
    RouteWaypointLatDeg,
    RouteWaypointLonDeg,
    RouteWaypointBearingTrueDeg,
    RouteWaypointBearingMagneticDeg,
    RouteWaypointDistanceNmi,
    RouteWaypointToId,
    RouteWaypointFromId,
    RouteWaypointArrivalCircleEntered,
    RouteWaypointPerpendicularPassed,
    RouteWaypointArrivalRadiusNmi,
    RouteWaypointArrivalId,

    TrawlHeadropeToFootropeM,
    TrawlHeadropeToBottomM,
    TrawlDoorCenterlineOffsetM,
    TrawlDoorAlongCenterlineM,
    TrawlCartesianCenterlineOffsetM,
    TrawlCartesianAlongCenterlineM,
    TrawlDepthBelowSurfaceM,
    TrawlRelativeRangeM,
    TrawlRelativeBearingDeg,
    TrawlTrueRangeM,
    TrawlTrueBearingDeg,

    AisTargetsObject,
    AisOwnVesselObject,
    AisSafetyObject,
    AisDataLinkStatusObject,
    DscStructuredNotification,
    InmarsatSafetyNetStructuredNotification,
    NavtexStructuredNotification,
    AlertStructuredNotification,
    MobStructuredNotification,
    LegacyCommObject,

    NotificationText,
    NotificationEvent,
};

} // namespace signalk_mini
