#pragma once
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <ship_data_model.hpp>
namespace nmea0183{
enum class Status:uint8_t{Applied,ParsedIgnored,Unsupported,InvalidChecksum,Malformed};
template<typename Real>constexpr Real pi_v(){return static_cast<Real>(3.1415926535897932384626433832795L);}template<typename Real>constexpr Real deg_to_rad(Real d){return d*pi_v<Real>()/static_cast<Real>(180);}template<typename Real>constexpr Real knots_to_mps(Real k){return k*static_cast<Real>(0.51444444444444444444L);}inline uint8_t hx(char c){if(c>='0'&&c<='9')return c-'0';if(c>='A'&&c<='F')return 10+c-'A';return 255;}inline char hd(uint8_t v){return char(v<10?'0'+v:'A'+v-10);}inline uint8_t checksum_body(const char*b,size_t n){uint8_t c=0;for(size_t i=0;i<n;i++)c^=uint8_t(b[i]);return c;}inline bool append_checksum(const char*b,char*out,size_t cap){size_t n=strlen(b);if(cap<n+5)return false;uint8_t c=checksum_body(b,n);out[0]='$';memcpy(out+1,b,n);out[n+1]='*';out[n+2]=hd((c>>4)&15);out[n+3]=hd(c&15);out[n+4]=0;return true;}
struct Field{const char*p;size_t n;};struct Sentence{char body[96];Field f[24];size_t n=0;};inline bool type_is(Field t,char a,char b,char c){return t.n>=3&&t.p[t.n-3]==a&&t.p[t.n-2]==b&&t.p[t.n-1]==c;}template<typename Real>bool real(Field f,Real&v){if(!f.p||!f.n||f.n>=24)return false;char tmp[24];memcpy(tmp,f.p,f.n);tmp[f.n]=0;char*e=nullptr;long double x=strtold(tmp,&e);if(e==tmp)return false;v=static_cast<Real>(x);return true;}inline bool ch(Field f,char&c){if(!f.p||!f.n)return false;c=f.p[0];return true;}template<typename Real>bool latlon(Field f,Field h,bool lat,Real&out){Real ddmm{};char hemi=0;if(!real<Real>(f,ddmm)||!ch(h,hemi))return false;int digits=lat?2:3;char tmp[16];if(f.n>=sizeof(tmp))return false;memcpy(tmp,f.p,f.n);tmp[f.n]=0;tmp[digits]=0;Real deg=static_cast<Real>(strtol(tmp,nullptr,10));Real min=ddmm-deg*static_cast<Real>(100);out=deg+min/static_cast<Real>(60);if(hemi=='S'||hemi=='W')out=-out;return true;}inline Status parse(const char*line,Sentence&s){if(*line!='$')return Status::Malformed;++line;const char*star=strchr(line,'*');if(!star||!star[1]||!star[2])return Status::Malformed;size_t len=size_t(star-line);if(checksum_body(line,len)!=uint8_t((hx(star[1])<<4)|hx(star[2])))return Status::InvalidChecksum;memcpy(s.body,line,len);s.body[len]=0;char*st=s.body;s.n=0;for(size_t i=0;i<=len;i++)if(s.body[i]==','||s.body[i]==0){s.f[s.n++]={st,size_t(&s.body[i]-st)};s.body[i]=0;st=&s.body[i+1];}return Status::ParsedIgnored;}
template<typename Real,typename Sink>void set(ship_data_model::Value<Real>&slot,ship_data_model::FieldId id,Real v,Sink&sink,uint16_t src,uint64_t now){slot.set(v,now,src);sink.mark_changed(id,src,now);}template<typename Real,typename Sink>Status apply_sentence(const char*line,ship_data_model::DataModel<Real>&m,Sink&sink,uint16_t src,uint64_t now){Sentence s;auto ps=parse(line,s);if(ps!=Status::ParsedIgnored)return ps;Real a{},b{};char ok=0;if(type_is(s.f[0],'R','M','C')){if(s.n<9||!ch(s.f[2],ok)||ok!='A')return Status::ParsedIgnored;if(latlon<Real>(s.f[3],s.f[4],true,a)&&latlon<Real>(s.f[5],s.f[6],false,b)){set(m.navigation.latitude_deg,ship_data_model::FieldId::NavigationLatitudeDeg,a,sink,src,now);set(m.navigation.longitude_deg,ship_data_model::FieldId::NavigationLongitudeDeg,b,sink,src,now);}if(real<Real>(s.f[7],a))set(m.navigation.sog_mps,ship_data_model::FieldId::NavigationSogMps,knots_to_mps<Real>(a),sink,src,now);if(real<Real>(s.f[8],a))set(m.navigation.cog_deg,ship_data_model::FieldId::NavigationCogDeg,a,sink,src,now);return Status::Applied;}if(type_is(s.f[0],'H','D','T')){if(s.n>1&&real<Real>(s.f[1],a)){set(m.navigation.heading_true_deg,ship_data_model::FieldId::NavigationHeadingTrueDeg,a,sink,src,now);return Status::Applied;}}if(type_is(s.f[0],'M','W','V')){char ref=0,unit=0;if(s.n>5&&ch(s.f[2],ref)&&ref=='R'&&ch(s.f[4],unit)&&unit=='N'&&ch(s.f[5],ok)&&ok=='A'&&real<Real>(s.f[1],a)&&real<Real>(s.f[3],b)){set(m.wind.apparent_angle_deg,ship_data_model::FieldId::WindApparentAngleDeg,a,sink,src,now);set(m.wind.apparent_speed_mps,ship_data_model::FieldId::WindApparentSpeedMps,knots_to_mps<Real>(b),sink,src,now);return Status::Applied;}}if(type_is(s.f[0],'D','P','T')){if(s.n>1&&real<Real>(s.f[1],a)){set(m.water.depth_below_transducer_m,ship_data_model::FieldId::WaterDepthBelowTransducerM,a,sink,src,now);return Status::Applied;}}return Status::Unsupported;}}
